# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79d441fe930a7a14d2a65348aa20d4362679f7fc5b8887d633ac02ca5ef71d8f075244c4aef43c8e1e4c018506bbe6428c5c67dabb84356ec135be544b16f77d

test:
  secret_key_base: b530b23d45da3046100fd983ca433949d1bf9379b76fdda296cfc26de68aa508cad0d5292377228839ea98b404ceaf69fb7a807bcc8fe34a282401e003c7df49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
